### ISSUE TITLE
GUI progress indication

### ISSUE THREAD

**Issue by docktermj** [Senzing/entity-search-web-app#69] opened 2019-10-03 15:10 UTC
**Is your feature request related to a problem? Please describe.**
This concerns the User Interface portion of the issue described at
https://github.com/Senzing/senzing-api-server/issues/97

In summary:

When clicking on an entity to get more details in the GUI, it takes 40 seconds before the details come up. The screen is blank until the details come up, so to the user it looks like bringing up the details "didn't work".

When the details do come up, it takes another 40 seconds to show the relationships for this entity.

    It would be nice to have some indication that the GUI is still working on bringing up the information.

**Comment by antaenc** [comment] 2019-10-03 19:19
Zach,

As per the other issue is this the web components in a browser or the i2 integration?

**Comment by docktermj** [comment] 2019-10-04 13:52
@ZackHill05  ^^^

**Comment by arawinters** [comment] 2019-10-07 17:20
this is a duplicate of #67
regression.

**Closed** 2019-11-20 00:16 UTC
Labels: duplicate

**Comment by docktermj** [comment] 2019-12-02 15:17
Pull requests:

1. https://github.com/Senzing/entity-search-web-app/pull/70
